#!/usr/bin/env python3
"""
Writes public/favicon.svg and public/favicon.ico from one palette.

Browsers still ask for /favicon.ico, and the one Astro ships is its own
rocket. Two files have to agree, and two hand-maintained files never do — so
this is the single source and both are generated. Re-run it after changing a
colour or a dimension; the check in check.sh fails if either file goes stale.

The mark is the smallest honest version of the design rather than a detailed
one scaled down: the room frame, and the ember inside it. A browser tab uses
16 pixels, and anything more than two shapes turns to mush there.

Colours are the day tokens (--paper, --frame, --ember) as literal values,
because a favicon is read by the operating system and cannot read this
stylesheet. It is deliberately not theme-aware: the mark should be the same
object in every tab, lit or dimmed.

  python3 scripts/make-favicon.py
"""


import pathlib
import sys

from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parent.parent
SVG = ROOT / "public" / "favicon.svg"
ICO = ROOT / "public" / "favicon.ico"

# The day tokens, by name. --paper / --frame / --ember in src/styles/tokens.css.
PALETTE = {"paper": "#f2ede4", "frame": "#ded4c3", "ember": "#a04720"}

# Geometry, in the SVG's 32-unit viewBox.
CANVAS = 32
INSET = 3.5  # the casing, held off the edge so it reads as a frame and not a border
STROKE = 2.0
RADIUS = 5.5  # the ember

SIZES = [16, 32]  # a browser tab; a bookmark bar

SVG_SOURCE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" \
aria-label="Pamela Roy">
  <!--
    GENERATED by scripts/make-favicon.py — edit that, not this.

    The room, at 32 pixels: the frame that holds the whole site, and the ember
    inside it. At the 16px a tab actually uses, anything more turns to mush, so
    this is the smallest honest version of the design rather than a detailed one
    scaled down. The dot is the lamp. The casing is the casing.

    Literal values, not tokens: an operating system reads this file and has
    never heard of the stylesheet. Deliberately not theme-aware — the mark
    should be the same object in every tab, lit or dimmed.
  -->
  <rect width="32" height="32" fill="{paper}" />
  <rect
    x="{inset}" y="{inset}" width="{box}" height="{box}"
    fill="none" stroke="{frame}" stroke-width="{stroke}"
  />
  <circle cx="16" cy="16" r="{radius}" fill="{ember}" />
</svg>
"""


def svg_text() -> str:
    return SVG_SOURCE.format(
        paper=PALETTE["paper"],
        frame=PALETTE["frame"],
        ember=PALETTE["ember"],
        inset=INSET,
        box=CANVAS - INSET * 2,
        stroke=STROKE,
        radius=RADIUS,
    )


def draw(size: int) -> Image.Image:
    """The room at one size: paper ground, casing, ember.

    Drawn at 8x and downsampled with LANCZOS. A 1px casing drawn directly at
    16px lands on half-pixels and comes back a grey blur, and that blur is the
    whole difference between a mark and a smudge.
    """
    s = size * 8
    k = s / CANVAS
    img = Image.new("RGB", (s, s), PALETTE["paper"])
    d = ImageDraw.Draw(img)

    d.rectangle(
        [INSET * k, INSET * k, s - INSET * k, s - INSET * k],
        outline=PALETTE["frame"],
        width=max(1, round(STROKE * k)),
    )
    r = RADIUS * k
    d.ellipse([s / 2 - r, s / 2 - r, s / 2 + r, s / 2 + r], fill=PALETTE["ember"])

    return img.resize((size, size), Image.LANCZOS)


def write_ico(frames: list[Image.Image]) -> None:
    """Assemble the ICO container from the frames as drawn.

    PIL can save an .ico, but only by downscaling one base image, and its base
    here would have to be either 16px (so the 32px entry is missing) or 32px
    (so the 16px entry is a second-hand resample of a resample). Each frame
    here was supersampled at its own size and knows best, so the container is
    written directly. The format is a 6-byte header, a 16-byte directory entry
    per image, then the payloads — and since Vista an entry may be a whole PNG,
    which is both smaller and lossless.
    """
    import io
    import struct

    payloads = []
    for frame in frames:
        buf = io.BytesIO()
        frame.save(buf, format="PNG")
        payloads.append(buf.getvalue())

    out = bytearray(struct.pack("<HHH", 0, 1, len(payloads)))
    offset = 6 + 16 * len(payloads)

    for frame, payload in zip(frames, payloads):
        n = frame.width
        out += struct.pack(
            "<BBBBHHII",
            n if n < 256 else 0,  # 0 means 256
            n if n < 256 else 0,
            0,  # palette size; 0 for truecolour
            0,  # reserved
            1,  # colour planes
            32,  # bits per pixel
            len(payload),
            offset,
        )
        offset += len(payload)

    for payload in payloads:
        out += payload

    ICO.write_bytes(bytes(out))


def main() -> int:
    frames = [draw(n) for n in SIZES]

    SVG.write_text(svg_text())
    write_ico(frames)

    # A contact sheet to look at, because a favicon you cannot see is a
    # favicon you have not checked. 16px is blown up with NEAREST: that is what
    # a tab really shows, and a smoothed version would hide a bad mark.
    sheet = Image.new("RGB", (16 * 8 + 32 * 4 + 40, 32 * 4 + 20), PALETTE["paper"])
    sheet.paste(frames[0].resize((16 * 8, 16 * 8), Image.NEAREST), (10, 10))
    sheet.paste(
        frames[1].resize((32 * 4, 32 * 4), Image.NEAREST), (10 + 16 * 8 + 20, 10)
    )
    sheet.save("/tmp/pamshots-favicon.png")

    for name, value in PALETTE.items():
        print(f"  {name:<6} {value}")
    print(f"  wrote {SVG.relative_to(ROOT)} and {ICO.relative_to(ROOT)}")
    print(f"  sizes {', '.join(f'{n}x{n}' for n in SIZES)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
